services:
  - type: web
    name: backdoor-gmail-tool
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y wget gnupg unzip xvfb libxi6 libgconf-2-4 fonts-liberation \
      libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcups2 libdbus-1-3 \
      libdrm2 libgbm1 libgtk-3-0 libnspr4 libnss3 libxcomposite1 libxdamage1 \
      libxfixes3 libxkbcommon0 libxrandr2 xdg-utils
      pip install -r requirements.txt
      playwright install chromium
      playwright install-deps
    startCommand: gunicorn --bind 0.0.0.0:$PORT "app:create_app()" --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: PROXY_LIST
        sync: false
      - key: DEFAULT_PROXY_TYPE
        value: http
    plan: free
    autoDeploy: false
    healthCheckPath: /
    # domains: [] # Optionally, leave empty or omit entirely